// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7O3N-OHJ2F4tx7XR4bSoY-vX9vKvY-Es',
    appId: '1:803978748369:web:d73e3a20387842e4bc40f0',
    messagingSenderId: '803978748369',
    projectId: 'fashion-b3eb0',
    authDomain: 'fashion-b3eb0.firebaseapp.com',
    storageBucket: 'fashion-b3eb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Kfg8I0KAxtBb1kjZb0JdHRoej72RerI',
    appId: '1:803978748369:android:75d768b20a6a533bbc40f0',
    messagingSenderId: '803978748369',
    projectId: 'fashion-b3eb0',
    storageBucket: 'fashion-b3eb0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw2tmIWi05XQvpnUEONM7P_vC-GhC8fGk',
    appId: '1:803978748369:ios:91e0d9414c5425e2bc40f0',
    messagingSenderId: '803978748369',
    projectId: 'fashion-b3eb0',
    storageBucket: 'fashion-b3eb0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw2tmIWi05XQvpnUEONM7P_vC-GhC8fGk',
    appId: '1:803978748369:ios:91e0d9414c5425e2bc40f0',
    messagingSenderId: '803978748369',
    projectId: 'fashion-b3eb0',
    storageBucket: 'fashion-b3eb0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7O3N-OHJ2F4tx7XR4bSoY-vX9vKvY-Es',
    appId: '1:803978748369:web:a8e71d0ee003a8a1bc40f0',
    messagingSenderId: '803978748369',
    projectId: 'fashion-b3eb0',
    authDomain: 'fashion-b3eb0.firebaseapp.com',
    storageBucket: 'fashion-b3eb0.firebasestorage.app',
  );
}
